#!/bin/bash
############################
# install
# This script creates symlinks from the home directory to any desired dotfiles in $HOME/dotfiles
############################


git submodule init 
git submodule update

if [[ $(printf "${PWD##*/}") != "dotfiles" ]]; then
	printf "CD to dotfiles dir or check its name first"
	exit
fi


############################
# check if using zsh
############################
#if $(printf $0) != "-zsh"; then
#        which zsh &>/dev/null
#        [ $? -eq 0 ] || printf "Install zsh before this script continues" && exit 
#    printf "Please set zsh as your default shell to zsh with chsh /bin/zsh before running this script" && exit
#fi

############################
# osx homebrew init
############################
# if [ "$(uname -s)" = "Darwin" ]; then
#     if [ "$(uwhich brew)" != "/usr/local/bin/brew" ]; then
#         /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#     fi
#     brew update
#     brew install wget
#     brew upgrade
#     brew install coreutils --default-names
# fi


#dir="$HOME/dotfiles"                    # dotfiles directory
olddir="$HOME/dotfiles_old"             # old dotfiles backup directory

GLOBIGNORE=".git:.gitignore:.gitmodules:install"; files=(.*)


##########

# create dotfiles_old in homedir
if [ ! -d "$olddir" ]
then
    printf "Creating $olddir for backup of any existing dotfiles in $HOME"
	mkdir -p $olddir
	printf "...done"
fi




# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for f in ${files[*]}; do
    if [ -f "$HOME/$f" ] || [ -d "$HOME/$f" ]; then
    	echo "file exists"
    	if [ ! -L "$HOME/$f" ]; then
    		echo "not a symlink"
    		printf "\n Moving $HOME/$f to $olddir/$f\n"
 			mv --backup "$HOME/$f" "$HOME/dotfiles_old/$f"
 			printf "\n Linking $HOME/$f to $(pwd)/$f\n"
    		ln -s "$(pwd)/$f" "$HOME/$f"
 		else
 			echo  "is a symlink"
 		fi
    else
    	echo "dopesnt exsit"
    	printf "\n Linking $HOME/$f to $(pwd)/$f\n"
    	ln -s "$(pwd)/$f" "$HOME/$f"
    fi
done
