set nocompatible
colo Despacio
syntax on
filetype indent plugin on
set hidden
set wildmenu
set showcmd
set ignorecase
set smartcase
set autoindent
set laststatus=2
set ruler
set visualbell
set confirm
set number
set mouse=a
autocmd FileType text setlocal textwidth=78
set backspace=indent,eol,start
let g:airline_powerline_fonts = 1
let g:airline_theme='tomorrow'
