#!/bin/bash
DISPLAY=:0
if !(pgrep pulseaudio)
then
	pulseaudio -D
fi

if !(pgrep mopidy)
then
	until ping -c1 last.fm &>/dev/null; do :; done
	/usr/bin/mopidy 2>&1 | sudo sed -e '/New MPD connection/d;w /var/log/mopidy.log'
fi
