'use strict';(function(m){if(void 0!==rea.globals._content)console.warn('content: Stop here, cause a second Tampermonkey instance was detected!\nThis can be caused by using "document.write" at Userscripts.\nSee https://code.google.com/p/chromium/issues/detail?id=253388 for more information');else{rea.globals._content=!0;var h;m.Registry=function(){var d={},e=[],b=function(){e=e.filter(function(a){var b=!1;a.r.forEach(function(a){d[a]||(b=!0)});if(b)return!0;a.fn()})},c=function(a,c,e){d[a]=e;b()},
a=function(a){a=d[a];return a instanceof Function?a():a};return{register:c,registerRaw:c,get:a,getRaw:a,require:function(a,c){e.push({r:a,fn:c});b()}}}();var q=function(){var d=function(b){return({}.toString.apply(b).match(/\s([a-z|A-Z]+)/)||[null,b&&"INPUT"===b.nodeName?"HTMLInputElement":"Object"])[1]},e=function(b){if("Object"==d(b)){var c=[],a;for(a in b)b.hasOwnProperty(a)&&c.push(a+":"+e(b[a]));return"{"+c.join(",")+"}"}if("Array"==d(b)){var k=[];b.forEach(function(a){k.push(e(a))});return"["+
k.join(",")+"]"}return void 0===b?"undefined":null===b?"null":"Function"==d(b)?b.toString():'"'+b.toString()+'"'};return{createUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var c=16*Math.random()|0;return("x"==b?c:c&3|8).toString(16)})},processQueue:function(b){for(var c;c=b.shift();)c()},serialize:e,toType:d}}(),y=function(){var d={_content:!0,JSHINT:!0},e=/(webkitStorageInfo|webkitIDB.*|webkitIndexedDB|webkitOfflineAudioContext|webkitAudioContext|webkitURL|webkitSpeech.*|Bluetooth.*|MIDI.*|StorageManager)/;
return function(){var b={},c,a,k=Object.getOwnPropertyNames(window),x=function(a,b){for(;(a=Object.getPrototypeOf(a))&&a!==Object.prototype;)b=b.concat(Object.getOwnPropertyNames(a));return b}(window,[]);c=0;for(a=null;a=x[c];c++)d[a]||e.exec(a)||(2<a.length&&"on"===a.substr(0,2)?b[a]={proto:!0,event:!0}:b[a]={proto:!0});c=0;for(a=null;a=k[c];c++)d[a]||b[a]||e.exec(a)||(2<a.length&&"on"===a.substr(0,2)?b[a]={window:!0,event:!0}:b[a]={window:!0});var f={addEventListener:{window:1},alert:{window:1},
atob:{window:1},blur:{window:1},btoa:{window:1},clearInterval:{window:1},clearTimeout:{window:1},close:{window:1},confirm:{window:1},decodeURI:{window:1},decodeURIComponent:{window:1},dispatchEvent:{window:1},encodeURI:{window:1},encodeURIComponent:{window:1},find:{window:1},focus:{window:1},getComputedStyle:{window:1},getSelection:{window:1},isFinite:{window:1},isNaN:{window:1},location:{window:1},open:{window:1},openDialog:{window:1},parseFloat:{window:1},parseInt:{window:1},postMessage:{window:1},
print:{window:1},prompt:{window:1},removeEventListener:{window:1},resizeBy:{window:1},resizeTo:{window:1},scroll:{window:1},scrollBy:{window:1},scrollByLines:{window:1},scrollByPages:{window:1},scrollTo:{window:1},setInterval:{window:1},setTimeout:{window:1},stop:{window:1}};Object.keys(f).forEach(function(a){b[a]||(b[a]=f[a])});return b}}(),f=q.createUUID(),r=window.self==window.top,v=0,p,g=function(d){var e=function(){return d.dispatchEvent.apply(d,arguments)},b=function(){return d.addEventListener.apply(d,
arguments)},c=function(){return d.removeEventListener.apply(d,arguments)},a=function(a,b){var c=d.createEvent("MutationEvent");c.initMutationEvent(a,!1,!1,null,null,null,JSON.stringify(b),c.ADDITION);return c},k=function(a,b){var c;a&&(c=m[a])&&(c(b),delete m[a])},f,u,h,g,l=1,m={};return{init:function(c){g||(g=c);h="2P_"+g;u="2C_"+g;b(u,function(b){var c=JSON.parse(b.attrName);"message.response"==c.m?k(c.r,c.a):f&&f(c,c.r?function(b){b=a(h,{m:"message.response",a:b,r:c.r});e(b)}:function(){})},!1)},
send:function(b,c,d){if(d){var k=++l;m[l]=d;d=k}else d=null;b=a(h,{m:b,a:c,r:d});e(b)},onMessage:{addListener:function(a){f=a}},cleanup:function(){c(u,f,!1)}}}(document),w=function(){var d={},e,b=function(b){var a=[],k=[],e=function(){f=k=a=null;delete d[b]},f={postMessage:function(a){g.send("port.message",{response_id:b,value:a})},onMessage:{addListener:function(b){a.push(b)}},onDisconnect:{addListener:function(a){k.push(a)}},disconnect:function(){g.send("port.message",{response_id:b,disconnect:!0});
e()}};d[b]={message:function(b){a&&a.forEach(function(a){a(b)})},disconnect:function(a){k&&k.forEach(function(b){b(a)});e()}};return f};return{message:function(c){var a;c.connect?e&&e(c.destination,b(c.response_id)):(a=d[c.response_id])?c.disconnect?a.disconnect():a.message(c.value):h&&console.warn("ports: unkown id",c.response_id,c)},connect:function(c){var a=q.createUUID();g.send("port.message",{response_id:a,connect:!0,destination:c});return b(a)},onConnect:{addListener:function(b){e=b}}}}(),l=
function(){var d,e,b=[],c=[],a=function(){h&&console.log("content: detected DOMContentLoaded "+f);e=!0;window.removeEventListener("DOMContentLoaded",a,!1);a=null;q.processQueue(b)},k=function(){h&&console.log("content: detected load "+f);d=e=!0;g.cleanup();q.processQueue(c)};window.addEventListener("DOMContentLoaded",a,!1);window.addEventListener("load",a,!1);var g={registerDomListener:function(a){e||d?a():b.push(a)},registerPageListener:function(a){d?a():c.push(a)},forcedLoad:function(){d||e||!k||
(h&&console.log("content: use forced load "+f),k(!0))},seen:function(){var a={};a.__defineGetter__("load",function(){return d});a.__defineGetter__("DOMContentLoaded",function(){return e});return a}(),cleanup:function(){a&&(window.removeEventListener("DOMContentLoaded",a,!1),a=null);k&&(window.removeEventListener("load",k,!1),k=null)}};return g}(),n=function(){return{init:function(d){p.inject("("+p.backup+')(window, document,"'+d+'",'+h+");\n")},cleanup:function(){g.send("cleanup")},next:function(d,
e,b){var c={short_id:rea.runtime.short_id};"inIncognitoContext downloadMode enforce_strict_mode measure_scripts version external_connect".split(" ").forEach(function(a){c[a]=d[a]});c.sandbox_allow_getters=!0;h&&(l.seen.load?console.log("content: Start ENV with page loaded "+f):l.seen.DOMContentLoaded?console.log("content: Start ENV with DOMContentLoaded "+f):console.log("content: Start ENV normally "+f));var a=d.scripts.map(function(a){return{header:a.header,storage:a.storage,script:a.script,requires:a.requires,
code:a.code}});e=p.next(f,JSON.stringify(a),q.serialize(e),JSON.stringify(b),JSON.stringify(c),JSON.stringify({}),v,void 0,void 0,void 0,void 0,h,l.seen.load,l.seen.DOMContentLoaded,p.environment);g.send("next",{src:e})}}}(),t=function(){var d={registerMenuCommand:function(b){var c=rea.extension.connect("registerMenuCommand");c.onMessage.addListener(function(a){a.run&&null!==c&&b.postMessage("run")});c.onDisconnect.addListener(function(){b.disconnect()});b.onMessage.addListener(function(a){if("register"===
a.method){var b=a.name;c.postMessage({method:"registerMenuCommand",name:b,id:f,menuId:f+"#"+b,accessKey:a.accessKey})}});b.onDisconnect.addListener(function(){c.disconnect()})},openInTab:function(b){var c=rea.extension.connect("openInTab");c.onMessage.addListener(function(a){b.postMessage(a)});c.onDisconnect.addListener(function(){b.disconnect()});b.onMessage.addListener(function(a){if("openTab"==a.method){var b=a.url,d=a.options;if("boolean"===typeof d||void 0===d)d={loadInBackground:d};a=void 0===
d.active?void 0===d.loadInBackground?!1:!d.loadInBackground:d.active;d=void 0===d.insert?!0:d.insert;b&&0===b.search(/^\/\//)&&(b=location.protocol+b);c.postMessage({method:"openInTab",details:{url:b,options:{active:!!a,insert:!!d}}})}else"nameTab"==a.method?c.postMessage({method:"nameTab",name:a.name}):"closeTab"==a.method&&c.postMessage({method:"closeTab"})});b.onDisconnect.addListener(function(){c.disconnect()})},download:function(b){var c=rea.extension.connect("download");c.onMessage.addListener(function(a){b.postMessage(a)});
c.onDisconnect.addListener(function(){b.disconnect()});b.onMessage.addListener(function(a){a=a.details;a.url&&"/"===a.url[0]&&(a.url=location.origin+a.url);c.postMessage({method:"download",details:a,id:f})});b.onDisconnect.addListener(function(){c.disconnect()})},xhr:function(b){var c=rea.extension.connect("xhr");c.onMessage.addListener(function(a){b.postMessage(a)});c.onDisconnect.addListener(function(){b.disconnect()});b.onMessage.addListener(function(a){c.postMessage(a)});b.onDisconnect.addListener(function(){c.disconnect()})},
values:function(b){var c=rea.extension.connect("values");c.onMessage.addListener(function(a){b.postMessage(a)});c.onDisconnect.addListener(function(){b.disconnect()});b.onMessage.addListener(function(a){c.postMessage(a)});b.onDisconnect.addListener(function(){c.disconnect()})}},e={setClipboard:function(b,c){var a=b.content,d=b.info,e=typeof d,g="text",h="text/plain";"object"===e?(d.type&&(g=d.type),d.mimetype&&(h=d.mimetype)):"string"===e&&(g=d);rea.extension.sendMessage({method:"copyToClipboard",
data:{content:a,type:g,mimetype:h},id:f},function(){c()})},notification:function(b,c){b.method="notification";rea.extension.sendMessage(b,c)},syntaxCheck:function(b,c){b.method="syntaxCheck";rea.extension.sendMessage(b,c)},closeTab:function(b,c){rea.extension.sendMessage({method:"closeTab",id:f},function(a){a.error&&console.warn(a.error);c()})},focusTab:function(b,c){rea.extension.sendMessage({method:"focusTab",id:f},function(a){a.error&&console.warn(a.error);c()})},addStyle:function(b,c){try{var a=
document.createElement("style");a.textContent=b.css||"";b.id&&a.setAttribute("id",b.id);(document.head||document.body||document.documentElement||document).appendChild(a);c()}catch(d){console.warn("content: error adding style",d)}},tabsSet:function(b,c){b.method="setTab";rea.extension.sendMessage(b,function(){c()})},tabsGet:function(b,c){b.method="getTab";rea.extension.sendMessage(b,function(a){c(a.data)})},tabsGetAll:function(b,c){b.method="getTabs";rea.extension.sendMessage(b,function(a){c(a.data)})}};
return{init:function(){},getApi:function(){var b={};[e,d].forEach(function(c){Object.keys(c).map(function(a){b["GM_"+a]=c[a]})});return b},processMessage:function(b,c,a){if(b=e[b])return b(c,a);a()},processConnect:function(b,c){var a;if(a=d[b])return a(c)}}}();rea.extension.onMessage.addListener(function(d,e,b){d.id&&d.id!=f?console.warn("content: Not for me! "+f.substr(0,10)+"!="+d.id):"fastExec"==d.method?(b({late:rea.globals.done}),rea.globals.done||(m.tm_info=d)):"executeScript"==d.method?d.url&&
0!==window.location.href.search(d.url)?h&&console.log("exec: URL doesn't match",window.location,d):d.topframe&&!r?h&&console.log("exec: topframe doesn't match",window.self,d):g.send("executeScript",d):"onLoad"==d.method?(document.readyState&&"complete"!==document.readyState||l.forcedLoad(),b({})):r&&("loadUrl"==d.method?(window.location=d.url,b({})):"reload"==d.method?(window.location.reload(),b({})):"confirm"==d.method?window.setTimeout(function(){var c=window.confirm(d.msg);b({confirm:c})},100):
"showMsg"==d.method?window.setTimeout(function(){window.setTimeout(function(){window.alert(d.msg)},1);b({})},100):"setForeignAttr"==d.method?(g.send(d.method,d),b({})):window.console.log("content: unknown method "+d.method))});w.onConnect.addListener(function(d,e){t.processConnect(d,e)});g.onMessage.addListener(function(d,e){if("document.write"==d.m){var b=document.documentElement;window.setTimeout(function(){b!==document.documentElement&&g.init()},0)}else"port.message"==d.m?w.message(d.a):"csp"==
d.m?p.inject('window["'+d.a.id+'"] = function() { '+d.a.src+" };\n"):"external.message"==d.m?rea.extension.sendMessage({method:"externalMessage",request:d.a},function(b){e(b)}):t.processMessage(d.m,d.a,e)});Registry.require(["page.js"],function(){p=Registry.getRaw("page.js");rea.globals.done=!1;var d=function(d,b){var c=1,a=function(){rea.extension.sendMessage({method:"prepare",id:f,topframe:r,url:window.location.href},function(f){rea.globals.done||(rea.globals.done=!0,void 0===f?(h&&console.debug("content: _early_ execution, connection to bg failed -> retry!"),
window.setTimeout(a,c),c*=2):f&&(f.contexters||f.scripts&&f.scripts.length||f.external_connect)?b(f):(n.cleanup(),d()))})};rea.content.onReady(a)};(function(e,b){h&&console.log("content: Started ("+f+", "+window.location.origin+window.location.pathname+")",m.tm_info);if(m.tm_info){var c=m.tm_info;delete m.tm_info;return c.contexters||c.scripts&&c.scripts.length||c.external_connect?(n.init(f),g.init(f),b(c,"sync")):e()}n.init(f);g.init(f);d(e,b);rea.FEATURES.RUNTIME.FAST_EXEC_SUPPORT&&m.__defineSetter__("tm_info",
function(a){rea.globals.done||(rea.globals.done=!0,h&&console.log("content: fast exec script ("+f+")"),a.contexters||a.scripts&&a.scripts.length?b(a,"fast"):(n.cleanup(),e()))})})(function(){h&&console.log("content: disable event processing for "+f);l.cleanup();n.cleanup();g.cleanup()},function(d,b){v=d.logLevel;h|=60<=v;l.registerDomListener(function(){g.send("DOMContentLoaded")});l.registerPageListener(function(){g.send("load")});h&&console.log("content: "+(b||"normal")+" start event processing for "+
f+" ("+d.scripts.length+" to run)");t.init(d.scripts);n.next(d,t.getApi(),y());r||window.addEventListener("unload",function(){rea.extension.sendMessage({method:"unLoad",id:f,topframe:!1,url:window.location.href},function(){});l.cleanup();n.cleanup();g.cleanup()},!1)})})}})(window);
