Registry.require(["crcrc","helper","layout/default/htmlutil","i18n","layout/default/layout_helper"],function(){var u=rea.FEATURES,r=Registry.get("crcrc").cr,h=Registry.get("crcrc").crc,y=Registry.get("helper"),t=Registry.get("layout/default/htmlutil"),k=Registry.get("i18n"),x=Registry.get("layout"),z=Registry.get("layout/default/layout_helper"),v=z.images;x.render(function(){var p={};z.addStyle();var x=function(b,a){var d=[];if(a.sub_menu_item){if(a.items.length){var c=h("table","actiontable","actiontable-"+
a.name);A(c,a.items);d.push(c)}}else if(c=null,a.image?c=t.createImage(v.get(a.image),a.name,a.id,null,""):a.enabler&&(c=t.createImage(rea.extension.getURL(p.enabled?"/layout/default/images/button_ok.png":"/layout/default/images/cancel.png"),a.name,a.uuid,null,"")),c&&d.push(c),a.url||a.urls){for(var c=r("span",a.name,a.id,"urls"),e=a.urls||[a],f=0;f<e.length;f++){var g=e[f],q=document.createElement("span");q.textContent=g.name;var w=a.urls?q:b;w.url=g.url;w.newtab=g.newtab;w.addEventListener("click",
function(){D(this.url,this.newtab)});$(w).addClass("clickable");c.appendChild(q);f<e.length-1&&(g=document.createElement("span"),g.textContent=" | ",c.appendChild(g))}d.push(c)}else if(a.menucmd){var l=document.createElement("span");b.id=a.id;e=function(){E(this.id,function(){u.ACTIONMENU.CLOSE_ALLOWED&&window.close()})};b.addEventListener("click",e);$(b).addClass("clickable");l.textContent=a.name;a.accessKey&&(c=a.accessKey[0].toUpperCase(),F(c,e,b)?(e=new RegExp(c,"i"),f=l.textContent.search(e),
g=[],-1==f&&(l.textContent+=" ("+c+")",f=l.textContent.search(e)),g.push({text:l.textContent.substr(0,f)}),g.push({text:l.textContent.substr(f,1),class:"underlined"}),g.push({text:l.textContent.substr(f+1)}),l.textContent="",g.forEach(function(c){var b=h("span",c.class||"",a.id,c);b.textContent=c.text;l.appendChild(b)})):console.warn("Registering keyboard shortcut for '"+a.name+"' failed"));d.push(l)}else if(a.button)c=h("span",a.display||"",a.name,a.id,"bu",!0),c.textContent=a.name,b.key=a.id,b.warning=
a.warning,b.reload=a.reload,b.data=a.data,b.addEventListener("click",function(){var a=!0;this.warning&&(a=G(this.warning));a&&H(this.key,{reload:this.reload,data:this.data})}),$(b).addClass("clickable"),d.push(c);else if(a.userscript){var c=h("div","clickable",a.name,a.uuid,"ai"),n;if(a.uuid&&(f=null,f=a.blacklisted?"enabler_warning":a.enabled?a.contexter?"enabler_enabled enabler_later":"enabler_enabled":"enabler_disabled",g=a.blacklisted?k.getMessage("This_script_is_blacklisted_"):a.enabled?k.getMessage("Enabled"):
k.getMessage("Disabled"),e=function(a){a&&(a.button&2||a.button&1||a.ctrlKey||a.metaKey)?(window.open(rea.extension.getURL("options.html")+"#nav="+this.key),a.stopPropagation()):I(this.uuid,"enabled",!this.oldvalue)},f=t.createEnabler(f,a.uuid,"enabled",{append:"enabled",disabled:a.blacklisted,title:g},e),f.oldvalue=a.enabled,d.push(f),f=r("div",a.name,a.uuid,"name"),f.textContent=k.getTranslation(a,"name"),c.appendChild(f),c.uuid=a.uuid,c.oldvalue=a.enabled,c.key=a.uuid,c.addEventListener("click",
e),a.blacklisted&&(b.setAttribute("title",k.getMessage("This_script_is_blacklisted_")),$(c).addClass("crossedout")),e=[],a.nnew||a.system||!a.origin||(f=h("div","action_issue",a.name,a.uuid,"action_issue"),q=t.createImage(v.get("flag"),"",a.uuid,"issue",k.getMessage("Report_an_issue_to_the_script_hoster_")),g=h("span","",a.name,a.uuid,"action_issue_expl"),g.textContent=k.getMessage("Report_an_issue_to_the_script_hoster_").split(/[\.\(]+/)[0],f.appendChild([q,g]),$(f).click(function(){B(a.uuid,"hoster")}),
e.push(f)),a.nnew||a.system||!a.support||(f=h("div","action_issue",a.name,a.uuid,"action_bug"),q=t.createImage(v.get("bug"),"",a.uuid,"bug",k.getMessage("Report_a_bug")),g=h("span","",a.name,a.uuid,"action_issue_expl"),g.textContent=k.getMessage("Report_a_bug"),f.appendChild([q,g]),$(f).click(function(){B(a.uuid,"author")}),e.push(f)),e.length)){n=h("div","actionenablercol",a.name,a.uuid,"actionenablercol");f=h("img","actionenabler clickable",a.name,a.uuid,"actionenabler");f.src=v.get("enabler");
$("body").click(function(){$(".action_issues").hide()});$(f).click(function(a){var c=$(n).find(".action_issues");$(c).is(":visible")||$(".action_issues").hide();c.toggle();a.stopPropagation()});var m=h("div","action_issues",a.name,a.uuid,"action_bug");e.forEach(function(a){m.appendChild(a)});m.setAttribute("style","display:none;");n.appendChild(m);n.appendChild(f)}d.push(c);n&&d.push(n)}else c=r("span",a.name,a.id,"ai"),c.textContent=a.name,d.push(c);return d},A=function(b,a,d){Object.keys(a).forEach(function(c){var e=
a[c];if(!b)if(d[e.pos])e.items&&e.items.length&&$(d[e.pos]).show();else{console.warn("Warn(cAm): unknown pos "+e.pos);return}var f=(c=b||d[e.pos])?r("tr",e.name,e.uuid||e.id,"outer"):null,g=x(f,e);if(g&&g.length){c.appendChild(f);var h;for(c=0;h=g[c];c++){var k=c==g.length-1?3-c:0,l=r("td","actiontd",e.name,e.uuid||e.id,c);0<k&&l.setAttribute("colspan",k);h&&l.appendChild(h);f.appendChild(l)}}})},C=function(b,a){var d=$("#action"),c=r("div");c.setAttribute("id","action");d.replaceWith(c);var e=h("table",
"actionlayout","actionlayout");c.appendChild(e);c=h("tr","actionpostr","hor");d=h("td","actionpostd","hor_west");c.appendChild(d);e.appendChild(c);var f=h("table","actionregion","top"),g=h("table","actionregion","right"),k,m=h("table","actionregion","left"),l=h("table","actionregion","bottom");if(2<Math.min(p.action_menu_columns,u.ACTIONMENU.COLUMNS)){k=h("table","actionregion","center");var n=h("td","actionpostd","hor_center"),e=h("td","actionpostd","hor_east");n.appendChild(k);c.appendChild(n);
c.appendChild(e)}else 1<Math.min(p.action_menu_columns,u.ACTIONMENU.COLUMNS)?(k=g,e=h("td","actionpostd","hor_east"),c.appendChild(e)):k=e=m;$([k,g]).hide();d.appendChild(f);e.appendChild(g);d.appendChild(m);d.appendChild(l);A(null,b,{top:f,left:m,center:k,right:g,bottom:l})},D=function(b,a){try{var d=function(){a&&u.ACTIONMENU.CLOSE_ALLOWED&&window.close()};a?sendMessage({method:"newTab",url:b},d):rea.tabs.getSelected(null,function(c){rea.tabs.sendMessage(c.id,{method:"loadUrl",url:b,newtab:a},d)})}catch(c){console.warn("lU:",
c)}},G=function(b){var a=confirm(b.msg),d={};a&&b.ok?d=b.ok:!a&&b.cancel&&(d=b.cancel);if(b.ok||b.cancel)a=!0;d.url&&sendMessage({method:"newTab",url:d.url},function(a){});return a},B=function(b,a,d){try{sendMessage({method:"reportAnIssue",uuid:b,to:a},function(a){d&&d()})}catch(c){console.warn("raI:",c)}},H=function(b,a){try{sendMessage({method:"buttonPress",name:b,data:a.data},function(b){a.reload&&rea.page.reload()})}catch(d){console.warn("rSU:",d)}},m={},J=function(b,a,d){document.body.addEventListener("keydown",
function(a){a.altKey||a.ctrlKey||a.shiftKey||Object.keys(m).forEach(function(b){(b=m[b])&&a.keyCode==b.key&&b.cb.apply(b.elem||window,[])})},!1)},F=function(b,a,d){b=b.charCodeAt(0);if(m[b])return console.log("MenuCmdKeyListener: ...failed!"),!1;m[b]={key:b,cb:a,elem:d};return!0},E=function(b,a){try{sendMessage({method:"execMenuCmd",id:b},function(b){a&&a()})}catch(d){console.warn("Error(eMC):",d)}},I=function(b,a,d){try{b={method:"modifyScriptOptions",uuid:b},a&&""!=a&&(b[a]=d),sendMessage(b,function(a){document.getElementById("action").innerHTML=
"";a&&(a.i18n&&k.setLocale(a.i18n),a.items&&(a.options&&(p=y.assign(p,a.options)),C(a.items)))})}catch(c){console.warn("Error(mSo): "+c.message)}};rea.extension.onMessage.addListener(function(b,a,d){"updateActions"==b.method?rea.page.reload():console.log("onMessage: Unknown method '"+b.method+"'")});(function(b,a){sendMessage({method:"loadTree",referrer:b},function(b){b.options&&(p=y.assign(p,b.options));b.i18n&&k.setLocale(b.i18n);a(b.items)})})("actions",function(b){J();C(b)})})});
